modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-zigbee-dc-module
name: Zigbee Device-Connector
description: "PLACEHOLDER for standalone zigbee dc module"
version: v0.0.7
type: device-connector
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MGW_MQTT_BROKER
          template: "tcp://{ref}:1881"
          services:
            - mgw-zigbee-dc
services:
  mgw-zigbee-dc:
    name: mgw-zigbee-dc
    image: ghcr.io/senergy-platform/mgw-zigbee-dc:v1.0.4